//go:build !ignore_autogenerated

/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	corev1 "k8s.io/api/core/v1"
	networkingv1 "k8s.io/api/networking/v1"
	apiextensionsv1 "k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1"
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	"k8s.io/apimachinery/pkg/util/intstr"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *APIComponentSpec) DeepCopyInto(out *APIComponentSpec) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	out.Image = in.Image
	in.WorkloadCommonSpec.DeepCopyInto(&out.WorkloadCommonSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new APIComponentSpec.
func (in *APIComponentSpec) DeepCopy() *APIComponentSpec {
	if in == nil {
		return nil
	}
	out := new(APIComponentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *APITokenSecretSpec) DeepCopyInto(out *APITokenSecretSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new APITokenSecretSpec.
func (in *APITokenSecretSpec) DeepCopy() *APITokenSecretSpec {
	if in == nil {
		return nil
	}
	out := new(APITokenSecretSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AdvancedResourcePatch) DeepCopyInto(out *AdvancedResourcePatch) {
	*out = *in
	out.Target = in.Target
	in.Patch.DeepCopyInto(&out.Patch)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AdvancedResourcePatch.
func (in *AdvancedResourcePatch) DeepCopy() *AdvancedResourcePatch {
	if in == nil {
		return nil
	}
	out := new(AdvancedResourcePatch)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AdvancedResourcePatchTarget) DeepCopyInto(out *AdvancedResourcePatchTarget) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AdvancedResourcePatchTarget.
func (in *AdvancedResourcePatchTarget) DeepCopy() *AdvancedResourcePatchTarget {
	if in == nil {
		return nil
	}
	out := new(AdvancedResourcePatchTarget)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AdvancedSpec) DeepCopyInto(out *AdvancedSpec) {
	*out = *in
	if in.ResourcePatches != nil {
		in, out := &in.ResourcePatches, &out.ResourcePatches
		*out = make([]AdvancedResourcePatch, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ExtraResources != nil {
		in, out := &in.ExtraResources, &out.ExtraResources
		*out = make([]apiextensionsv1.JSON, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AdvancedSpec.
func (in *AdvancedSpec) DeepCopy() *AdvancedSpec {
	if in == nil {
		return nil
	}
	out := new(AdvancedSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuthExternalSpec) DeepCopyInto(out *AuthExternalSpec) {
	*out = *in
	in.OAuth2.DeepCopyInto(&out.OAuth2)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuthExternalSpec.
func (in *AuthExternalSpec) DeepCopy() *AuthExternalSpec {
	if in == nil {
		return nil
	}
	out := new(AuthExternalSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuthSpec) DeepCopyInto(out *AuthSpec) {
	*out = *in
	if in.External != nil {
		in, out := &in.External, &out.External
		*out = new(AuthExternalSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.AuthentikBlueprints != nil {
		in, out := &in.AuthentikBlueprints, &out.AuthentikBlueprints
		*out = new(AuthentikBlueprintsSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuthSpec.
func (in *AuthSpec) DeepCopy() *AuthSpec {
	if in == nil {
		return nil
	}
	out := new(AuthSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuthStatus) DeepCopyInto(out *AuthStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuthStatus.
func (in *AuthStatus) DeepCopy() *AuthStatus {
	if in == nil {
		return nil
	}
	out := new(AuthStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuthentikBlueprintsSpec) DeepCopyInto(out *AuthentikBlueprintsSpec) {
	*out = *in
	out.APITokenSecretRef = in.APITokenSecretRef
	if in.RedirectURIs != nil {
		in, out := &in.RedirectURIs, &out.RedirectURIs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.GroupBindings != nil {
		in, out := &in.GroupBindings, &out.GroupBindings
		*out = make([]AuthentikGroupBindingSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuthentikBlueprintsSpec.
func (in *AuthentikBlueprintsSpec) DeepCopy() *AuthentikBlueprintsSpec {
	if in == nil {
		return nil
	}
	out := new(AuthentikBlueprintsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuthentikGroupBindingSpec) DeepCopyInto(out *AuthentikGroupBindingSpec) {
	*out = *in
	if in.Permissions != nil {
		in, out := &in.Permissions, &out.Permissions
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuthentikGroupBindingSpec.
func (in *AuthentikGroupBindingSpec) DeepCopy() *AuthentikGroupBindingSpec {
	if in == nil {
		return nil
	}
	out := new(AuthentikGroupBindingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutoscalingSpec) DeepCopyInto(out *AutoscalingSpec) {
	*out = *in
	if in.TargetCPUUtilizationPercentage != nil {
		in, out := &in.TargetCPUUtilizationPercentage, &out.TargetCPUUtilizationPercentage
		*out = new(int32)
		**out = **in
	}
	if in.TargetMemoryUtilizationPercentage != nil {
		in, out := &in.TargetMemoryUtilizationPercentage, &out.TargetMemoryUtilizationPercentage
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutoscalingSpec.
func (in *AutoscalingSpec) DeepCopy() *AutoscalingSpec {
	if in == nil {
		return nil
	}
	out := new(AutoscalingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BackendStatus) DeepCopyInto(out *BackendStatus) {
	*out = *in
	out.DB = in.DB
	out.S3 = in.S3
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BackendStatus.
func (in *BackendStatus) DeepCopy() *BackendStatus {
	if in == nil {
		return nil
	}
	out := new(BackendStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BackendStorageSpec) DeepCopyInto(out *BackendStorageSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BackendStorageSpec.
func (in *BackendStorageSpec) DeepCopy() *BackendStorageSpec {
	if in == nil {
		return nil
	}
	out := new(BackendStorageSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BackendsSpec) DeepCopyInto(out *BackendsSpec) {
	*out = *in
	in.DB.DeepCopyInto(&out.DB)
	in.S3.DeepCopyInto(&out.S3)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BackendsSpec.
func (in *BackendsSpec) DeepCopy() *BackendsSpec {
	if in == nil {
		return nil
	}
	out := new(BackendsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BackupPolicyStatus) DeepCopyInto(out *BackupPolicyStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BackupPolicyStatus.
func (in *BackupPolicyStatus) DeepCopy() *BackupPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(BackupPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComponentImagesSpec) DeepCopyInto(out *ComponentImagesSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComponentImagesSpec.
func (in *ComponentImagesSpec) DeepCopy() *ComponentImagesSpec {
	if in == nil {
		return nil
	}
	out := new(ComponentImagesSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComponentReplicaStatus) DeepCopyInto(out *ComponentReplicaStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComponentReplicaStatus.
func (in *ComponentReplicaStatus) DeepCopy() *ComponentReplicaStatus {
	if in == nil {
		return nil
	}
	out := new(ComponentReplicaStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DBBackendSpec) DeepCopyInto(out *DBBackendSpec) {
	*out = *in
	if in.External != nil {
		in, out := &in.External, &out.External
		*out = new(DBExternalSpec)
		**out = **in
	}
	if in.Bundled != nil {
		in, out := &in.Bundled, &out.Bundled
		*out = new(DBBundledSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.CNPG != nil {
		in, out := &in.CNPG, &out.CNPG
		*out = new(DBCNPGSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.ApplyFixtures != nil {
		in, out := &in.ApplyFixtures, &out.ApplyFixtures
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DBBackendSpec.
func (in *DBBackendSpec) DeepCopy() *DBBackendSpec {
	if in == nil {
		return nil
	}
	out := new(DBBackendSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DBBackendStatus) DeepCopyInto(out *DBBackendStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DBBackendStatus.
func (in *DBBackendStatus) DeepCopy() *DBBackendStatus {
	if in == nil {
		return nil
	}
	out := new(DBBackendStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DBBundledSpec) DeepCopyInto(out *DBBundledSpec) {
	*out = *in
	out.Storage = in.Storage
	in.Resources.DeepCopyInto(&out.Resources)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DBBundledSpec.
func (in *DBBundledSpec) DeepCopy() *DBBundledSpec {
	if in == nil {
		return nil
	}
	out := new(DBBundledSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DBCNPGBackupSpec) DeepCopyInto(out *DBCNPGBackupSpec) {
	*out = *in
	out.ObjectStore = in.ObjectStore
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DBCNPGBackupSpec.
func (in *DBCNPGBackupSpec) DeepCopy() *DBCNPGBackupSpec {
	if in == nil {
		return nil
	}
	out := new(DBCNPGBackupSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DBCNPGMonitoringSpec) DeepCopyInto(out *DBCNPGMonitoringSpec) {
	*out = *in
	if in.EnablePodMonitor != nil {
		in, out := &in.EnablePodMonitor, &out.EnablePodMonitor
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DBCNPGMonitoringSpec.
func (in *DBCNPGMonitoringSpec) DeepCopy() *DBCNPGMonitoringSpec {
	if in == nil {
		return nil
	}
	out := new(DBCNPGMonitoringSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DBCNPGObjectStoreSpec) DeepCopyInto(out *DBCNPGObjectStoreSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DBCNPGObjectStoreSpec.
func (in *DBCNPGObjectStoreSpec) DeepCopy() *DBCNPGObjectStoreSpec {
	if in == nil {
		return nil
	}
	out := new(DBCNPGObjectStoreSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DBCNPGRestoreSpec) DeepCopyInto(out *DBCNPGRestoreSpec) {
	*out = *in
	if in.TargetImmediate != nil {
		in, out := &in.TargetImmediate, &out.TargetImmediate
		*out = new(bool)
		**out = **in
	}
	out.ObjectStore = in.ObjectStore
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DBCNPGRestoreSpec.
func (in *DBCNPGRestoreSpec) DeepCopy() *DBCNPGRestoreSpec {
	if in == nil {
		return nil
	}
	out := new(DBCNPGRestoreSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DBCNPGSpec) DeepCopyInto(out *DBCNPGSpec) {
	*out = *in
	out.Storage = in.Storage
	in.Resources.DeepCopyInto(&out.Resources)
	out.Backup = in.Backup
	in.Restore.DeepCopyInto(&out.Restore)
	in.Monitoring.DeepCopyInto(&out.Monitoring)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DBCNPGSpec.
func (in *DBCNPGSpec) DeepCopy() *DBCNPGSpec {
	if in == nil {
		return nil
	}
	out := new(DBCNPGSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DBExternalSpec) DeepCopyInto(out *DBExternalSpec) {
	*out = *in
	out.Auth = in.Auth
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DBExternalSpec.
func (in *DBExternalSpec) DeepCopy() *DBExternalSpec {
	if in == nil {
		return nil
	}
	out := new(DBExternalSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EndpointStatus) DeepCopyInto(out *EndpointStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EndpointStatus.
func (in *EndpointStatus) DeepCopy() *EndpointStatus {
	if in == nil {
		return nil
	}
	out := new(EndpointStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EndpointURLSpec) DeepCopyInto(out *EndpointURLSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EndpointURLSpec.
func (in *EndpointURLSpec) DeepCopy() *EndpointURLSpec {
	if in == nil {
		return nil
	}
	out := new(EndpointURLSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HTTPRouteBackendRef) DeepCopyInto(out *HTTPRouteBackendRef) {
	*out = *in
	if in.Weight != nil {
		in, out := &in.Weight, &out.Weight
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HTTPRouteBackendRef.
func (in *HTTPRouteBackendRef) DeepCopy() *HTTPRouteBackendRef {
	if in == nil {
		return nil
	}
	out := new(HTTPRouteBackendRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HTTPRouteHostSpec) DeepCopyInto(out *HTTPRouteHostSpec) {
	*out = *in
	if in.Hostnames != nil {
		in, out := &in.Hostnames, &out.Hostnames
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.DefaultFilters != nil {
		in, out := &in.DefaultFilters, &out.DefaultFilters
		*out = make([]apiextensionsv1.JSON, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Filters != nil {
		in, out := &in.Filters, &out.Filters
		*out = make([]apiextensionsv1.JSON, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Rules != nil {
		in, out := &in.Rules, &out.Rules
		*out = make([]HTTPRouteRule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HTTPRouteHostSpec.
func (in *HTTPRouteHostSpec) DeepCopy() *HTTPRouteHostSpec {
	if in == nil {
		return nil
	}
	out := new(HTTPRouteHostSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HTTPRouteMatch) DeepCopyInto(out *HTTPRouteMatch) {
	*out = *in
	if in.Path != nil {
		in, out := &in.Path, &out.Path
		*out = new(HTTPRoutePathMatch)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HTTPRouteMatch.
func (in *HTTPRouteMatch) DeepCopy() *HTTPRouteMatch {
	if in == nil {
		return nil
	}
	out := new(HTTPRouteMatch)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HTTPRouteParentRef) DeepCopyInto(out *HTTPRouteParentRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HTTPRouteParentRef.
func (in *HTTPRouteParentRef) DeepCopy() *HTTPRouteParentRef {
	if in == nil {
		return nil
	}
	out := new(HTTPRouteParentRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HTTPRoutePathMatch) DeepCopyInto(out *HTTPRoutePathMatch) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HTTPRoutePathMatch.
func (in *HTTPRoutePathMatch) DeepCopy() *HTTPRoutePathMatch {
	if in == nil {
		return nil
	}
	out := new(HTTPRoutePathMatch)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HTTPRouteRule) DeepCopyInto(out *HTTPRouteRule) {
	*out = *in
	if in.Matches != nil {
		in, out := &in.Matches, &out.Matches
		*out = make([]HTTPRouteMatch, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.BackendRefs != nil {
		in, out := &in.BackendRefs, &out.BackendRefs
		*out = make([]HTTPRouteBackendRef, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Filters != nil {
		in, out := &in.Filters, &out.Filters
		*out = make([]apiextensionsv1.JSON, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HTTPRouteRule.
func (in *HTTPRouteRule) DeepCopy() *HTTPRouteRule {
	if in == nil {
		return nil
	}
	out := new(HTTPRouteRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HTTPRouteSpec) DeepCopyInto(out *HTTPRouteSpec) {
	*out = *in
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.ParentRefs != nil {
		in, out := &in.ParentRefs, &out.ParentRefs
		*out = make([]HTTPRouteParentRef, len(*in))
		copy(*out, *in)
	}
	in.API.DeepCopyInto(&out.API)
	in.UI.DeepCopyInto(&out.UI)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HTTPRouteSpec.
func (in *HTTPRouteSpec) DeepCopy() *HTTPRouteSpec {
	if in == nil {
		return nil
	}
	out := new(HTTPRouteSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImageSpec) DeepCopyInto(out *ImageSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImageSpec.
func (in *ImageSpec) DeepCopy() *ImageSpec {
	if in == nil {
		return nil
	}
	out := new(ImageSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IngressHostSpec) DeepCopyInto(out *IngressHostSpec) {
	*out = *in
	if in.Paths != nil {
		in, out := &in.Paths, &out.Paths
		*out = make([]networkingv1.HTTPIngressPath, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IngressHostSpec.
func (in *IngressHostSpec) DeepCopy() *IngressHostSpec {
	if in == nil {
		return nil
	}
	out := new(IngressHostSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IngressSpec) DeepCopyInto(out *IngressSpec) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.TLS != nil {
		in, out := &in.TLS, &out.TLS
		*out = make([]networkingv1.IngressTLS, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.API.DeepCopyInto(&out.API)
	in.UI.DeepCopyInto(&out.UI)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IngressSpec.
func (in *IngressSpec) DeepCopy() *IngressSpec {
	if in == nil {
		return nil
	}
	out := new(IngressSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkPolicyRulesSpec) DeepCopyInto(out *NetworkPolicyRulesSpec) {
	*out = *in
	if in.Ingress != nil {
		in, out := &in.Ingress, &out.Ingress
		*out = make([]networkingv1.NetworkPolicyIngressRule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Egress != nil {
		in, out := &in.Egress, &out.Egress
		*out = make([]networkingv1.NetworkPolicyEgressRule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkPolicyRulesSpec.
func (in *NetworkPolicyRulesSpec) DeepCopy() *NetworkPolicyRulesSpec {
	if in == nil {
		return nil
	}
	out := new(NetworkPolicyRulesSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkPolicySpec) DeepCopyInto(out *NetworkPolicySpec) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	in.API.DeepCopyInto(&out.API)
	in.UI.DeepCopyInto(&out.UI)
	in.Worker.DeepCopyInto(&out.Worker)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkPolicySpec.
func (in *NetworkPolicySpec) DeepCopy() *NetworkPolicySpec {
	if in == nil {
		return nil
	}
	out := new(NetworkPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OAuth2ClientCredentialsSecretSpec) DeepCopyInto(out *OAuth2ClientCredentialsSecretSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OAuth2ClientCredentialsSecretSpec.
func (in *OAuth2ClientCredentialsSecretSpec) DeepCopy() *OAuth2ClientCredentialsSecretSpec {
	if in == nil {
		return nil
	}
	out := new(OAuth2ClientCredentialsSecretSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OAuth2Spec) DeepCopyInto(out *OAuth2Spec) {
	*out = *in
	if in.RequiredScopes != nil {
		in, out := &in.RequiredScopes, &out.RequiredScopes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Algorithms != nil {
		in, out := &in.Algorithms, &out.Algorithms
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	out.ClientCredentialsSecret = in.ClientCredentialsSecret
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OAuth2Spec.
func (in *OAuth2Spec) DeepCopy() *OAuth2Spec {
	if in == nil {
		return nil
	}
	out := new(OAuth2Spec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PDBSpec) DeepCopyInto(out *PDBSpec) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.MinAvailable != nil {
		in, out := &in.MinAvailable, &out.MinAvailable
		*out = new(intstr.IntOrString)
		**out = **in
	}
	if in.MaxUnavailable != nil {
		in, out := &in.MaxUnavailable, &out.MaxUnavailable
		*out = new(intstr.IntOrString)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PDBSpec.
func (in *PDBSpec) DeepCopy() *PDBSpec {
	if in == nil {
		return nil
	}
	out := new(PDBSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderDomainStatus) DeepCopyInto(out *ProviderDomainStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderDomainStatus.
func (in *ProviderDomainStatus) DeepCopy() *ProviderDomainStatus {
	if in == nil {
		return nil
	}
	out := new(ProviderDomainStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderStatus) DeepCopyInto(out *ProviderStatus) {
	*out = *in
	out.DB = in.DB
	out.S3 = in.S3
	out.Auth = in.Auth
	out.Routing = in.Routing
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderStatus.
func (in *ProviderStatus) DeepCopy() *ProviderStatus {
	if in == nil {
		return nil
	}
	out := new(ProviderStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PublicEndpointSpec) DeepCopyInto(out *PublicEndpointSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PublicEndpointSpec.
func (in *PublicEndpointSpec) DeepCopy() *PublicEndpointSpec {
	if in == nil {
		return nil
	}
	out := new(PublicEndpointSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReplicaStatus) DeepCopyInto(out *ReplicaStatus) {
	*out = *in
	out.API = in.API
	out.Worker = in.Worker
	out.UI = in.UI
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReplicaStatus.
func (in *ReplicaStatus) DeepCopy() *ReplicaStatus {
	if in == nil {
		return nil
	}
	out := new(ReplicaStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResolvedGeneratedSecretsStatus) DeepCopyInto(out *ResolvedGeneratedSecretsStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResolvedGeneratedSecretsStatus.
func (in *ResolvedGeneratedSecretsStatus) DeepCopy() *ResolvedGeneratedSecretsStatus {
	if in == nil {
		return nil
	}
	out := new(ResolvedGeneratedSecretsStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResolvedImageStatus) DeepCopyInto(out *ResolvedImageStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResolvedImageStatus.
func (in *ResolvedImageStatus) DeepCopy() *ResolvedImageStatus {
	if in == nil {
		return nil
	}
	out := new(ResolvedImageStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResolvedResourceStatus) DeepCopyInto(out *ResolvedResourceStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResolvedResourceStatus.
func (in *ResolvedResourceStatus) DeepCopy() *ResolvedResourceStatus {
	if in == nil {
		return nil
	}
	out := new(ResolvedResourceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResolvedRouteStatus) DeepCopyInto(out *ResolvedRouteStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResolvedRouteStatus.
func (in *ResolvedRouteStatus) DeepCopy() *ResolvedRouteStatus {
	if in == nil {
		return nil
	}
	out := new(ResolvedRouteStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResolvedStatus) DeepCopyInto(out *ResolvedStatus) {
	*out = *in
	out.Images = in.Images
	out.Versions = in.Versions
	out.GeneratedSecrets = in.GeneratedSecrets
	out.Resources = in.Resources
	out.Routes = in.Routes
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResolvedStatus.
func (in *ResolvedStatus) DeepCopy() *ResolvedStatus {
	if in == nil {
		return nil
	}
	out := new(ResolvedStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResolvedVersionStatus) DeepCopyInto(out *ResolvedVersionStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResolvedVersionStatus.
func (in *ResolvedVersionStatus) DeepCopy() *ResolvedVersionStatus {
	if in == nil {
		return nil
	}
	out := new(ResolvedVersionStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *S3BackendSpec) DeepCopyInto(out *S3BackendSpec) {
	*out = *in
	if in.External != nil {
		in, out := &in.External, &out.External
		*out = new(S3ExternalSpec)
		**out = **in
	}
	if in.Bundled != nil {
		in, out := &in.Bundled, &out.Bundled
		*out = new(S3BundledSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.RustFSOperator != nil {
		in, out := &in.RustFSOperator, &out.RustFSOperator
		*out = new(S3RustFSOperatorSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new S3BackendSpec.
func (in *S3BackendSpec) DeepCopy() *S3BackendSpec {
	if in == nil {
		return nil
	}
	out := new(S3BackendSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *S3BackendStatus) DeepCopyInto(out *S3BackendStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new S3BackendStatus.
func (in *S3BackendStatus) DeepCopy() *S3BackendStatus {
	if in == nil {
		return nil
	}
	out := new(S3BackendStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *S3BundledServiceSpec) DeepCopyInto(out *S3BundledServiceSpec) {
	*out = *in
	if in.Ports != nil {
		in, out := &in.Ports, &out.Ports
		*out = make([]corev1.ServicePort, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new S3BundledServiceSpec.
func (in *S3BundledServiceSpec) DeepCopy() *S3BundledServiceSpec {
	if in == nil {
		return nil
	}
	out := new(S3BundledServiceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *S3BundledSpec) DeepCopyInto(out *S3BundledSpec) {
	*out = *in
	out.Storage = in.Storage
	in.Resources.DeepCopyInto(&out.Resources)
	out.PublicEndpoint = in.PublicEndpoint
	in.Service.DeepCopyInto(&out.Service)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new S3BundledSpec.
func (in *S3BundledSpec) DeepCopy() *S3BundledSpec {
	if in == nil {
		return nil
	}
	out := new(S3BundledSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *S3EndpointSpec) DeepCopyInto(out *S3EndpointSpec) {
	*out = *in
	out.Default = in.Default
	out.Public = in.Public
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new S3EndpointSpec.
func (in *S3EndpointSpec) DeepCopy() *S3EndpointSpec {
	if in == nil {
		return nil
	}
	out := new(S3EndpointSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *S3ExternalSpec) DeepCopyInto(out *S3ExternalSpec) {
	*out = *in
	out.Endpoint = in.Endpoint
	out.Auth = in.Auth
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new S3ExternalSpec.
func (in *S3ExternalSpec) DeepCopy() *S3ExternalSpec {
	if in == nil {
		return nil
	}
	out := new(S3ExternalSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *S3PublicEndpointSpec) DeepCopyInto(out *S3PublicEndpointSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new S3PublicEndpointSpec.
func (in *S3PublicEndpointSpec) DeepCopy() *S3PublicEndpointSpec {
	if in == nil {
		return nil
	}
	out := new(S3PublicEndpointSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *S3RustFSOperatorBucketSpec) DeepCopyInto(out *S3RustFSOperatorBucketSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new S3RustFSOperatorBucketSpec.
func (in *S3RustFSOperatorBucketSpec) DeepCopy() *S3RustFSOperatorBucketSpec {
	if in == nil {
		return nil
	}
	out := new(S3RustFSOperatorBucketSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *S3RustFSOperatorSpec) DeepCopyInto(out *S3RustFSOperatorSpec) {
	*out = *in
	if in.Pools != nil {
		in, out := &in.Pools, &out.Pools
		*out = make([]S3RustFSPoolSpec, len(*in))
		copy(*out, *in)
	}
	out.CredsSecret = in.CredsSecret
	if in.Env != nil {
		in, out := &in.Env, &out.Env
		*out = make([]corev1.EnvVar, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	out.PublicEndpoint = in.PublicEndpoint
	out.Bucket = in.Bucket
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new S3RustFSOperatorSpec.
func (in *S3RustFSOperatorSpec) DeepCopy() *S3RustFSOperatorSpec {
	if in == nil {
		return nil
	}
	out := new(S3RustFSOperatorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *S3RustFSPoolSpec) DeepCopyInto(out *S3RustFSPoolSpec) {
	*out = *in
	out.Storage = in.Storage
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new S3RustFSPoolSpec.
func (in *S3RustFSPoolSpec) DeepCopy() *S3RustFSPoolSpec {
	if in == nil {
		return nil
	}
	out := new(S3RustFSPoolSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SchemaMigrationStatus) DeepCopyInto(out *SchemaMigrationStatus) {
	*out = *in
	if in.LastAttemptTime != nil {
		in, out := &in.LastAttemptTime, &out.LastAttemptTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SchemaMigrationStatus.
func (in *SchemaMigrationStatus) DeepCopy() *SchemaMigrationStatus {
	if in == nil {
		return nil
	}
	out := new(SchemaMigrationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretKeyRefSpec) DeepCopyInto(out *SecretKeyRefSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretKeyRefSpec.
func (in *SecretKeyRefSpec) DeepCopy() *SecretKeyRefSpec {
	if in == nil {
		return nil
	}
	out := new(SecretKeyRefSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretKeySpec) DeepCopyInto(out *SecretKeySpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretKeySpec.
func (in *SecretKeySpec) DeepCopy() *SecretKeySpec {
	if in == nil {
		return nil
	}
	out := new(SecretKeySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretReferenceSpec) DeepCopyInto(out *SecretReferenceSpec) {
	*out = *in
	out.SecretKeys = in.SecretKeys
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretReferenceSpec.
func (in *SecretReferenceSpec) DeepCopy() *SecretReferenceSpec {
	if in == nil {
		return nil
	}
	out := new(SecretReferenceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretsSpec) DeepCopyInto(out *SecretsSpec) {
	*out = *in
	out.APIToken = in.APIToken
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretsSpec.
func (in *SecretsSpec) DeepCopy() *SecretsSpec {
	if in == nil {
		return nil
	}
	out := new(SecretsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceAccountSpec) DeepCopyInto(out *ServiceAccountSpec) {
	*out = *in
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceAccountSpec.
func (in *ServiceAccountSpec) DeepCopy() *ServiceAccountSpec {
	if in == nil {
		return nil
	}
	out := new(ServiceAccountSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServicePortsSpec) DeepCopyInto(out *ServicePortsSpec) {
	*out = *in
	if in.Ports != nil {
		in, out := &in.Ports, &out.Ports
		*out = make([]corev1.ServicePort, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServicePortsSpec.
func (in *ServicePortsSpec) DeepCopy() *ServicePortsSpec {
	if in == nil {
		return nil
	}
	out := new(ServicePortsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceSpec) DeepCopyInto(out *ServiceSpec) {
	*out = *in
	in.API.DeepCopyInto(&out.API)
	in.UI.DeepCopyInto(&out.UI)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceSpec.
func (in *ServiceSpec) DeepCopy() *ServiceSpec {
	if in == nil {
		return nil
	}
	out := new(ServiceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StorageBackend) DeepCopyInto(out *StorageBackend) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorageBackend.
func (in *StorageBackend) DeepCopy() *StorageBackend {
	if in == nil {
		return nil
	}
	out := new(StorageBackend)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *StorageBackend) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StorageBackendList) DeepCopyInto(out *StorageBackendList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]StorageBackend, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorageBackendList.
func (in *StorageBackendList) DeepCopy() *StorageBackendList {
	if in == nil {
		return nil
	}
	out := new(StorageBackendList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *StorageBackendList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StorageBackendResolvedStatus) DeepCopyInto(out *StorageBackendResolvedStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorageBackendResolvedStatus.
func (in *StorageBackendResolvedStatus) DeepCopy() *StorageBackendResolvedStatus {
	if in == nil {
		return nil
	}
	out := new(StorageBackendResolvedStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StorageBackendSpec) DeepCopyInto(out *StorageBackendSpec) {
	*out = *in
	out.TamossRef = in.TamossRef
	out.Endpoint = in.Endpoint
	out.Credentials = in.Credentials
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorageBackendSpec.
func (in *StorageBackendSpec) DeepCopy() *StorageBackendSpec {
	if in == nil {
		return nil
	}
	out := new(StorageBackendSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StorageBackendStatus) DeepCopyInto(out *StorageBackendStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	out.Resolved = in.Resolved
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorageBackendStatus.
func (in *StorageBackendStatus) DeepCopy() *StorageBackendStatus {
	if in == nil {
		return nil
	}
	out := new(StorageBackendStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Tamoss) DeepCopyInto(out *Tamoss) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Tamoss.
func (in *Tamoss) DeepCopy() *Tamoss {
	if in == nil {
		return nil
	}
	out := new(Tamoss)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Tamoss) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TamossList) DeepCopyInto(out *TamossList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Tamoss, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TamossList.
func (in *TamossList) DeepCopy() *TamossList {
	if in == nil {
		return nil
	}
	out := new(TamossList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TamossList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TamossReferenceSpec) DeepCopyInto(out *TamossReferenceSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TamossReferenceSpec.
func (in *TamossReferenceSpec) DeepCopy() *TamossReferenceSpec {
	if in == nil {
		return nil
	}
	out := new(TamossReferenceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TamossSpec) DeepCopyInto(out *TamossSpec) {
	*out = *in
	out.PublicEndpoint = in.PublicEndpoint
	in.API.DeepCopyInto(&out.API)
	in.Worker.DeepCopyInto(&out.Worker)
	in.UI.DeepCopyInto(&out.UI)
	out.Images = in.Images
	in.Backends.DeepCopyInto(&out.Backends)
	in.Auth.DeepCopyInto(&out.Auth)
	in.Ingress.DeepCopyInto(&out.Ingress)
	in.HTTPRoute.DeepCopyInto(&out.HTTPRoute)
	in.NetworkPolicy.DeepCopyInto(&out.NetworkPolicy)
	in.Service.DeepCopyInto(&out.Service)
	in.ServiceAccount.DeepCopyInto(&out.ServiceAccount)
	out.Secrets = in.Secrets
	if in.ImagePullSecrets != nil {
		in, out := &in.ImagePullSecrets, &out.ImagePullSecrets
		*out = make([]corev1.LocalObjectReference, len(*in))
		copy(*out, *in)
	}
	in.Advanced.DeepCopyInto(&out.Advanced)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TamossSpec.
func (in *TamossSpec) DeepCopy() *TamossSpec {
	if in == nil {
		return nil
	}
	out := new(TamossSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TamossStatus) DeepCopyInto(out *TamossStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	out.Replicas = in.Replicas
	out.Backends = in.Backends
	out.Auth = in.Auth
	out.Endpoints = in.Endpoints
	out.BackupPolicy = in.BackupPolicy
	out.Providers = in.Providers
	out.Resolved = in.Resolved
	out.Upgrade = in.Upgrade
	in.SchemaMigration.DeepCopyInto(&out.SchemaMigration)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TamossStatus.
func (in *TamossStatus) DeepCopy() *TamossStatus {
	if in == nil {
		return nil
	}
	out := new(TamossStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UIComponentSpec) DeepCopyInto(out *UIComponentSpec) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	out.Image = in.Image
	if in.Ports != nil {
		in, out := &in.Ports, &out.Ports
		*out = make([]corev1.ContainerPort, len(*in))
		copy(*out, *in)
	}
	in.WorkloadCommonSpec.DeepCopyInto(&out.WorkloadCommonSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UIComponentSpec.
func (in *UIComponentSpec) DeepCopy() *UIComponentSpec {
	if in == nil {
		return nil
	}
	out := new(UIComponentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UIIngressSpec) DeepCopyInto(out *UIIngressSpec) {
	*out = *in
	in.Web.DeepCopyInto(&out.Web)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UIIngressSpec.
func (in *UIIngressSpec) DeepCopy() *UIIngressSpec {
	if in == nil {
		return nil
	}
	out := new(UIIngressSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UpgradeStatus) DeepCopyInto(out *UpgradeStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpgradeStatus.
func (in *UpgradeStatus) DeepCopy() *UpgradeStatus {
	if in == nil {
		return nil
	}
	out := new(UpgradeStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkerComponentSpec) DeepCopyInto(out *WorkerComponentSpec) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	in.WorkloadCommonSpec.DeepCopyInto(&out.WorkloadCommonSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkerComponentSpec.
func (in *WorkerComponentSpec) DeepCopy() *WorkerComponentSpec {
	if in == nil {
		return nil
	}
	out := new(WorkerComponentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkloadCommonSpec) DeepCopyInto(out *WorkloadCommonSpec) {
	*out = *in
	if in.ReplicaCount != nil {
		in, out := &in.ReplicaCount, &out.ReplicaCount
		*out = new(int32)
		**out = **in
	}
	if in.Env != nil {
		in, out := &in.Env, &out.Env
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.EnvFrom != nil {
		in, out := &in.EnvFrom, &out.EnvFrom
		*out = make([]corev1.EnvFromSource, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.PodAnnotations != nil {
		in, out := &in.PodAnnotations, &out.PodAnnotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.PodLabels != nil {
		in, out := &in.PodLabels, &out.PodLabels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.PodSecurityContext != nil {
		in, out := &in.PodSecurityContext, &out.PodSecurityContext
		*out = new(corev1.PodSecurityContext)
		(*in).DeepCopyInto(*out)
	}
	if in.SecurityContext != nil {
		in, out := &in.SecurityContext, &out.SecurityContext
		*out = new(corev1.SecurityContext)
		(*in).DeepCopyInto(*out)
	}
	in.Resources.DeepCopyInto(&out.Resources)
	if in.LivenessProbe != nil {
		in, out := &in.LivenessProbe, &out.LivenessProbe
		*out = new(corev1.Probe)
		(*in).DeepCopyInto(*out)
	}
	if in.ReadinessProbe != nil {
		in, out := &in.ReadinessProbe, &out.ReadinessProbe
		*out = new(corev1.Probe)
		(*in).DeepCopyInto(*out)
	}
	if in.StartupProbe != nil {
		in, out := &in.StartupProbe, &out.StartupProbe
		*out = new(corev1.Probe)
		(*in).DeepCopyInto(*out)
	}
	if in.TerminationGracePeriodSeconds != nil {
		in, out := &in.TerminationGracePeriodSeconds, &out.TerminationGracePeriodSeconds
		*out = new(int64)
		**out = **in
	}
	if in.PreStopSleepSeconds != nil {
		in, out := &in.PreStopSleepSeconds, &out.PreStopSleepSeconds
		*out = new(int32)
		**out = **in
	}
	in.PDB.DeepCopyInto(&out.PDB)
	in.Autoscaling.DeepCopyInto(&out.Autoscaling)
	if in.Volumes != nil {
		in, out := &in.Volumes, &out.Volumes
		*out = make([]corev1.Volume, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.VolumeMounts != nil {
		in, out := &in.VolumeMounts, &out.VolumeMounts
		*out = make([]corev1.VolumeMount, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Tolerations != nil {
		in, out := &in.Tolerations, &out.Tolerations
		*out = make([]corev1.Toleration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Affinity != nil {
		in, out := &in.Affinity, &out.Affinity
		*out = new(corev1.Affinity)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkloadCommonSpec.
func (in *WorkloadCommonSpec) DeepCopy() *WorkloadCommonSpec {
	if in == nil {
		return nil
	}
	out := new(WorkloadCommonSpec)
	in.DeepCopyInto(out)
	return out
}
