apiVersion: tamoss.livewyer.io/v1alpha1
kind: PlatformDependencies
metadata:
  name: tamoss-platform
spec:
  role: platform-runtime-bom
  certManager:
    version: v1.20.2
    chart: jetstack/cert-manager
    chartVersion: v1.20.2
    source: https://github.com/cert-manager/cert-manager/releases/tag/v1.20.2
  traefik:
    version: v3.7.1
    chart: traefik/traefik
    chartVersion: 40.2.0
    source: https://github.com/traefik/traefik/releases/tag/v3.7.1
    crdManifest: deploy/platform/chart/files/traefik/traefik-crds.yaml
  authentik:
    version: 2026.2.3
    chart: authentik/authentik
    chartVersion: 2026.2.3
    source: https://github.com/goauthentik/authentik/releases/tag/version/2026.2.3
  cnpg:
    version: v1.29.1
    chart: cnpg/cloudnative-pg
    chartVersion: 0.28.2
    source: https://github.com/cloudnative-pg/cloudnative-pg/releases/tag/v1.29.1
  rustfsOperator:
    chartVersion: 0.1.0
    imageTag: 0.0.1
    repository: https://github.com/rustfs/operator.git
    ref: ff80d847806eb7cfc9c4a33769715a6b0f3145dd
    manifest: deploy/platform/chart/files/rustfs-operator/rustfs-operator.yaml
    crdManifest: deploy/platform/chart/files/rustfs-operator/tenant-crd.yaml
  rustfs:
    version: 1.0.0-beta.3
    source: https://github.com/rustfs/rustfs/releases/tag/1.0.0-beta.3
  compose:
    postgresImage: postgres:18.3
    rustfsImage: rustfs/rustfs:1.0.0-beta.3
