apiVersion: apps/v1
kind: Deployment
metadata:
  name: operator-controller-manager
  namespace: tamoss-system
spec:
  template:
    spec:
      containers:
        - name: manager
          imagePullPolicy: Never
