apiVersion: v1
kind: Namespace
metadata:
  name: tams
---
apiVersion: tamoss.livewyer.io/v1alpha1
kind: Tamoss
metadata:
  name: tamoss-edge
  namespace: tams
spec:
  profile: edge
  # serviceIdentity:
  #   name: Newsroom Archive
  #   description: Long-form newsroom archive, retained for 12 months.
