package main

import (
	"bufio"
	"context"
	"errors"
	"net"
	"net/http"
	"net/http/httptest"
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"

	appsv1 "k8s.io/api/apps/v1"
	batchv1 "k8s.io/api/batch/v1"
	corev1 "k8s.io/api/core/v1"
	discoveryv1 "k8s.io/api/discovery/v1"
	"k8s.io/client-go/rest"
	"sigs.k8s.io/controller-runtime/pkg/cache"

	tamossv1alpha1 "github.com/livewyer-ops/tamoss/operator/api/v1alpha1"
	"github.com/livewyer-ops/tamoss/operator/internal/consoleapi"
)

const testConsoleProof = "0123456789abcdef0123456789abcdef"

func TestConsoleAuthenticatorFromEnvironmentRequiresExplicitMode(t *testing.T) {
	clearConsoleAuthEnvironment(t)
	if _, _, err := consoleAuthenticatorFromEnvironment(); err == nil || !strings.Contains(err.Error(), consoleAuthModeEnv) {
		t.Fatalf("consoleAuthenticatorFromEnvironment() error = %v, want missing mode", err)
	}
}

func TestConsoleAuthenticatorFromEnvironmentAllowsExplicitDevelopmentMode(t *testing.T) {
	clearConsoleAuthEnvironment(t)
	t.Setenv(consoleAuthModeEnv, consoleAuthModeDevelopment)
	authenticator, cursorKey, err := consoleAuthenticatorFromEnvironment()
	if err != nil {
		t.Fatal(err)
	}
	identity, err := authenticator.Authenticate(httptest.NewRequest(http.MethodGet, consoleapi.RuntimePath, nil))
	if err != nil {
		t.Fatal(err)
	}
	if identity.Method != "development-anonymous" || !identity.CanView() {
		t.Fatalf("unexpected development identity: %#v", identity)
	}
	if cursorKey != nil {
		t.Fatalf("development cursor key = %x, want generated by the read store", cursorKey)
	}
}

func TestConsoleAuthenticatorFromEnvironmentAllowsFailClosedUnavailableMode(t *testing.T) {
	clearConsoleAuthEnvironment(t)
	t.Setenv(consoleAuthModeEnv, consoleAuthModeUnavailable)
	authenticator, cursorKey, err := consoleAuthenticatorFromEnvironment()
	if err != nil {
		t.Fatal(err)
	}
	if _, err := authenticator.Authenticate(httptest.NewRequest(http.MethodGet, consoleapi.RuntimePath, nil)); !errors.Is(err, consoleapi.ErrUnauthenticated) {
		t.Fatalf("unavailable authenticator error = %v, want %v", err, consoleapi.ErrUnauthenticated)
	}
	if cursorKey != nil {
		t.Fatalf("unavailable cursor key = %x, want generated by the read store", cursorKey)
	}
}

func TestConsoleAuthenticatorFromEnvironmentLoadsForwardAuthFiles(t *testing.T) {
	clearConsoleAuthEnvironment(t)
	proofPath := filepath.Join(t.TempDir(), "proof")
	if err := os.WriteFile(proofPath, []byte(testConsoleProof+"\n"), 0o600); err != nil {
		t.Fatal(err)
	}
	t.Setenv(consoleAuthModeEnv, consoleAuthModeForwardAuth)
	t.Setenv(consoleForwardAuthSecretFileEnv, proofPath)
	t.Setenv(consoleGroupRoleBindingsEnv, `[{"groupName":"tamoss-admins","permissions":["admin"]}]`)

	authenticator, cursorKey, err := consoleAuthenticatorFromEnvironment()
	if err != nil {
		t.Fatal(err)
	}
	request := httptest.NewRequest(http.MethodGet, consoleapi.RuntimePath, nil)
	request.Header.Set(consoleapi.ForwardAuthSecretHeader, testConsoleProof)
	request.Header.Set(consoleapi.ForwardAuthSubjectHeader, "user-123")
	request.Header.Set(consoleapi.ForwardAuthGroupsHeader, "tamoss-admins")
	identity, err := authenticator.Authenticate(request)
	if err != nil {
		t.Fatal(err)
	}
	if !identity.HasRole(consoleapi.RoleViewer) || !identity.HasRole(consoleapi.RoleOperator) || !identity.HasRole(consoleapi.RoleIngestRunner) {
		t.Fatalf("admin binding did not expand to all Console roles: %#v", identity)
	}
	if len(cursorKey) != 32 {
		t.Fatalf("forward-auth cursor key length = %d, want 32", len(cursorKey))
	}
}

func TestConsoleAuthenticatorFromEnvironmentRejectsInvalidForwardAuthConfig(t *testing.T) {
	tests := []struct {
		name         string
		mode         string
		secretPath   string
		bindingsJSON string
	}{
		{name: "unsupported mode", mode: "optional"},
		{name: "missing secret path", mode: consoleAuthModeForwardAuth, bindingsJSON: `[{"groupName":"viewers","permissions":["viewer"]}]`},
		{name: "relative secret path", mode: consoleAuthModeForwardAuth, secretPath: "proof", bindingsJSON: `[{"groupName":"viewers","permissions":["viewer"]}]`},
		{name: "missing bindings", mode: consoleAuthModeForwardAuth, secretPath: "valid"},
		{name: "invalid bindings", mode: consoleAuthModeForwardAuth, secretPath: "valid", bindingsJSON: `[{"groupName":"viewers","permissions":["owner"]}]`},
	}
	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			clearConsoleAuthEnvironment(t)
			t.Setenv(consoleAuthModeEnv, test.mode)
			secretPath := test.secretPath
			if secretPath == "valid" {
				secretPath = filepath.Join(t.TempDir(), "proof")
				if err := os.WriteFile(secretPath, []byte(testConsoleProof), 0o600); err != nil {
					t.Fatal(err)
				}
			}
			t.Setenv(consoleForwardAuthSecretFileEnv, secretPath)
			t.Setenv(consoleGroupRoleBindingsEnv, test.bindingsJSON)
			if _, _, err := consoleAuthenticatorFromEnvironment(); err == nil {
				t.Fatal("consoleAuthenticatorFromEnvironment() succeeded, want error")
			}
		})
	}
}

func TestReadForwardAuthSecretFileIsBounded(t *testing.T) {
	path := filepath.Join(t.TempDir(), "proof")
	if err := os.WriteFile(path, []byte(strings.Repeat("x", maxForwardAuthSecretFileSize+1)), 0o600); err != nil {
		t.Fatal(err)
	}
	if _, err := readForwardAuthSecretFile(path); err == nil {
		t.Fatal("readForwardAuthSecretFile() succeeded, want size error")
	}
}

func TestForwardAuthConfigDoesNotAcceptWrongProof(t *testing.T) {
	clearConsoleAuthEnvironment(t)
	path := filepath.Join(t.TempDir(), "proof")
	if err := os.WriteFile(path, []byte(testConsoleProof), 0o600); err != nil {
		t.Fatal(err)
	}
	t.Setenv(consoleAuthModeEnv, consoleAuthModeForwardAuth)
	t.Setenv(consoleForwardAuthSecretFileEnv, path)
	t.Setenv(consoleGroupRoleBindingsEnv, `[{"groupName":"viewers","permissions":["viewer"]}]`)
	authenticator, _, err := consoleAuthenticatorFromEnvironment()
	if err != nil {
		t.Fatal(err)
	}
	request := httptest.NewRequest(http.MethodGet, consoleapi.RuntimePath, nil)
	request.Header.Set(consoleapi.ForwardAuthSecretHeader, strings.Repeat("x", len(testConsoleProof)))
	request.Header.Set(consoleapi.ForwardAuthSubjectHeader, "user-123")
	request.Header.Set(consoleapi.ForwardAuthGroupsHeader, "viewers")
	if _, err := authenticator.Authenticate(request); !errors.Is(err, consoleapi.ErrUnauthenticated) {
		t.Fatalf("Authenticate() error = %v, want %v", err, consoleapi.ErrUnauthenticated)
	}
}

func TestRuntimeCacheScopesEveryInformer(t *testing.T) {
	namespaces := map[string]cache.Config{"tams": {}}
	scopes := runtimeCacheByObject(namespaces, "media")
	wantLabelSelector := instanceLabel + "=media"
	seen := map[string]bool{}
	for object, scope := range scopes {
		if len(scope.Namespaces) != 1 {
			t.Fatalf("%T cache namespaces = %#v, want only tams", object, scope.Namespaces)
		}
		if _, found := scope.Namespaces["tams"]; !found {
			t.Fatalf("%T cache namespaces = %#v, want tams", object, scope.Namespaces)
		}

		kind := ""
		switch object.(type) {
		case *tamossv1alpha1.Tamoss:
			kind = "Tamoss"
			if scope.Label != nil || scope.Field == nil || scope.Field.String() != "metadata.name=media" {
				t.Fatalf("Tamoss cache must select the exact instance name: %#v", scope)
			}
		case *tamossv1alpha1.StorageBackend:
			kind = "StorageBackend"
			if scope.Label != nil || scope.Field != nil {
				t.Fatalf("%T cache must be namespace-wide: %#v", object, scope)
			}
		case *corev1.Event:
			kind = "Event"
			if scope.Label != nil || scope.Field != nil {
				t.Fatalf("%T cache must be namespace-wide: %#v", object, scope)
			}
		case *appsv1.Deployment:
			kind = "Deployment"
		case *appsv1.ReplicaSet:
			kind = "ReplicaSet"
		case *corev1.Service:
			kind = "Service"
		case *discoveryv1.EndpointSlice:
			kind = "EndpointSlice"
		case *corev1.Pod:
			kind = "Pod"
		case *batchv1.Job:
			kind = "Job"
		default:
			t.Fatalf("unexpected runtime informer type %T", object)
		}
		if kind == "" {
			t.Fatalf("runtime informer kind was not classified for %T", object)
		}
		if kind != "Tamoss" && kind != "StorageBackend" && kind != "Event" {
			if scope.Field != nil || scope.Label == nil || scope.Label.String() != wantLabelSelector {
				t.Fatalf("%s cache label selector = %v, want %q", kind, scope.Label, wantLabelSelector)
			}
		}
		if seen[kind] {
			t.Fatalf("runtime informer/cache contains duplicate %s entries", kind)
		}
		seen[kind] = true
	}
	for _, kind := range []string{
		"Tamoss", "Deployment", "ReplicaSet", "Service", "EndpointSlice",
		"StorageBackend", "Pod", "Job", "Event",
	} {
		if !seen[kind] {
			t.Fatalf("runtime informer/cache is missing %s", kind)
		}
	}
	for object := range scopes {
		if _, found := object.(*tamossv1alpha1.IngestRun); found {
			t.Fatal("IngestRun must use bounded live GETs, not an informer")
		}
	}
}

type staticSnapshotSource struct{}

func (staticSnapshotSource) Snapshot(context.Context) (consoleapi.RuntimeSnapshot, error) {
	return consoleapi.RuntimeSnapshot{
		SchemaVersion: consoleapi.RuntimeSchemaVersion,
		Instance:      consoleapi.Instance{Name: "media", Phase: "Ready"},
	}, nil
}

// TestConsoleHTTPServerShutsDownPromptlyWithAnOpenEventStream reproduces the
// production shutdown path: Shutdown does not cancel in-flight request
// contexts, and an SSE heartbeat keeps the connection out of the idle set, so
// without the shutdown signal the grace period is burned in full and run()
// returns an error.
func TestConsoleHTTPServerShutsDownPromptlyWithAnOpenEventStream(t *testing.T) {
	ctx, stop := context.WithCancel(context.Background())
	t.Cleanup(stop)
	monitor := consoleapi.NewMonitor(staticSnapshotSource{})
	if err := monitor.Refresh(context.Background()); err != nil {
		t.Fatal(err)
	}
	handler := consoleapi.NewServer(
		monitor,
		consoleapi.NewDevelopmentAnonymousAuthenticator(),
		consoleapi.WithShutdownContext(ctx),
	).Handler()

	listener, err := net.Listen("tcp", "127.0.0.1:0")
	if err != nil {
		t.Fatal(err)
	}
	server := newConsoleHTTPServer(listener.Addr().String(), handler)
	served := make(chan error, 1)
	go func() { served <- server.Serve(listener) }()

	client := &http.Client{Transport: &http.Transport{}}
	t.Cleanup(client.CloseIdleConnections)
	response, err := client.Get("http://" + listener.Addr().String() + consoleapi.RuntimeEventsPath)
	if err != nil {
		t.Fatal(err)
	}
	t.Cleanup(func() { _ = response.Body.Close() })
	if response.StatusCode != http.StatusOK {
		t.Fatalf("event stream status = %d, want 200", response.StatusCode)
	}
	scanner := bufio.NewScanner(response.Body)
	streaming := false
	for scanner.Scan() {
		if strings.HasPrefix(scanner.Text(), "data: ") {
			streaming = true
			break
		}
	}
	if !streaming {
		t.Fatalf("the event stream produced no event: %v", scanner.Err())
	}

	stop()
	shutdownCtx, cancel := context.WithTimeout(context.Background(), shutdownGracePeriod)
	defer cancel()
	start := time.Now()
	if err := server.Shutdown(shutdownCtx); err != nil {
		t.Fatalf("Shutdown() error = %v, want a clean shutdown", err)
	}
	if elapsed := time.Since(start); elapsed > 2*time.Second {
		t.Fatalf("Shutdown() took %s with an open event stream, want a prompt close", elapsed)
	}
	if err := <-served; !errors.Is(err, http.ErrServerClosed) {
		t.Fatalf("Serve() error = %v, want %v", err, http.ErrServerClosed)
	}
}

func TestConsoleClientRateLimitsAbsorbOneWorstCaseHistoryTraversal(t *testing.T) {
	config := &rest.Config{}
	applyConsoleClientRateLimits(config)
	if config.QPS != consoleClientQPS || config.Burst != consoleClientBurst {
		t.Fatalf("rest config limits = %v/%d, want %v/%d",
			config.QPS, config.Burst, float32(consoleClientQPS), consoleClientBurst)
	}
	// The client-go defaults are QPS 5 and burst 10. One sparse history page can
	// issue up to 32 bounded List calls before the 4s request timeout expires,
	// and the snapshotter's live reads share the same limiter.
	const worstCaseListCallsPerRequest = 32
	if config.Burst < worstCaseListCallsPerRequest || config.QPS < worstCaseListCallsPerRequest {
		t.Fatalf("rest config limits %v/%d cannot absorb %d queued List calls",
			config.QPS, config.Burst, worstCaseListCallsPerRequest)
	}
}

func clearConsoleAuthEnvironment(t *testing.T) {
	t.Helper()
	for _, name := range []string{consoleAuthModeEnv, consoleForwardAuthSecretFileEnv, consoleGroupRoleBindingsEnv} {
		t.Setenv(name, "")
	}
}
