certManager:
  enabled: false

cnpg:
  enabled: false

rustfsOperator:
  enabled: false

authentik:
  enabled: false
  ingress:
    host: auth.tamoss.localtest.me
    tlsSecretName: authentik-localtest-tls

traefik:
  enabled: false
  crds:
    enabled: true
  replicas: 2
  image:
    repository: traefik
    tag: v3.7.1
    pullPolicy: IfNotPresent
  service:
    type: LoadBalancer
    nodePort: null
    annotations: {}

tls:
  mode: existing
  issuerName: tamoss-public
  acme:
    email: ""
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretName: ""
    http01:
      ingressClassName: traefik

clusterIssuer:
  selfSigned:
    enabled: false
    name: tamoss-selfsigned
