apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

patches:
  - target:
      group: tamoss.livewyer.io
      version: v1alpha1
      kind: Tamoss
    patch: |-
      - op: add
        path: /spec/publicEndpoint
        value:
          baseDomain: tamoss.localtest.me
      - op: add
        path: /spec/api
        value:
          env:
            TAMOSS_WEBHOOK_ALLOWED_HOSTS: .svc.cluster.local
          image:
            tag: dev
      - op: add
        path: /spec/worker
        value:
          env:
            TAMOSS_WEBHOOK_ALLOWED_HOSTS: .svc.cluster.local
      - op: add
        path: /spec/ui
        value:
          image:
            tag: dev
      - op: add
        path: /spec/backends
        value:
          s3:
            rustfsOperator:
              env:
                - name: RUSTFS_UNSAFE_BYPASS_DISK_CHECK
                  value: "true"
