{{- $pg := .Values.credentials.postgresql -}}
{{- if not $pg.existingSecret }}
{{- $pgName := include "tams-stack.postgresqlSecretName" . -}}
{{- $pgExisting := lookup "v1" "Secret" .Release.Namespace $pgName -}}
{{- $pgUserKey := default "username" $pg.secretKeys.username -}}
{{- $pgPasswordKey := default "password" $pg.secretKeys.password -}}
{{- $pgDatabaseKey := default "database" $pg.secretKeys.database -}}
{{- $pgUsername := default "tams" $pg.username -}}
{{- $pgPassword := "" -}}
{{- if $pg.password -}}
  {{- $pgPassword = $pg.password -}}
{{- else if and $pgExisting (hasKey $pgExisting.data $pgPasswordKey) -}}
  {{- $pgPassword = (index $pgExisting.data $pgPasswordKey | b64dec) -}}
{{- else -}}
  {{- $pgPassword = randAlphaNum 32 -}}
{{- end -}}
{{- $pgDatabase := default "tams" $pg.database -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $pgName }}
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  {{ $pgUserKey }}: {{ $pgUsername | quote }}
  {{ $pgPasswordKey }}: {{ $pgPassword | quote }}
  {{ $pgDatabaseKey }}: {{ $pgDatabase | quote }}
{{- end }}
{{- $s3 := .Values.credentials.rustfs -}}
{{- if not $s3.existingSecret }}
{{ if not $pg.existingSecret }}
---
{{ end }}
{{- $s3Name := include "tams-stack.rustfsSecretName" . -}}
{{- $s3Existing := lookup "v1" "Secret" .Release.Namespace $s3Name -}}
{{- $s3AccessKeyName := default "RUSTFS_ACCESS_KEY" $s3.secretKeys.accessKey -}}
{{- $s3SecretKeyName := default "RUSTFS_SECRET_KEY" $s3.secretKeys.secretKey -}}
{{- $s3AccessKey := "" -}}
{{- if $s3.accessKey -}}
  {{- $s3AccessKey = $s3.accessKey -}}
{{- else if and $s3Existing (hasKey $s3Existing.data $s3AccessKeyName) -}}
  {{- $s3AccessKey = (index $s3Existing.data $s3AccessKeyName | b64dec) -}}
{{- else -}}
  {{- $s3AccessKey = randAlphaNum 32 -}}
{{- end -}}
{{- $s3SecretKey := "" -}}
{{- if $s3.secretKey -}}
  {{- $s3SecretKey = $s3.secretKey -}}
{{- else if and $s3Existing (hasKey $s3Existing.data $s3SecretKeyName) -}}
  {{- $s3SecretKey = (index $s3Existing.data $s3SecretKeyName | b64dec) -}}
{{- else -}}
  {{- $s3SecretKey = randAlphaNum 32 -}}
{{- end -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $s3Name }}
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  {{ $s3AccessKeyName }}: {{ $s3AccessKey | quote }}
  {{ $s3SecretKeyName }}: {{ $s3SecretKey | quote }}
{{- end }}
