authentik:
  secret_key: tamoss-kind-authentik-secret-key-change-me
  bootstrap_token: tamoss-kind-authentik-api-token
  bootstrap_password: tamoss-kind-authentik-admin
  bootstrap_email: admin@tamoss.localtest.me
  postgresql:
    password: tamoss-kind-authentik-postgres

postgresql:
  enabled: true
  auth:
    password: tamoss-kind-authentik-postgres
    postgresPassword: tamoss-kind-authentik-postgres-admin

server:
  ingress:
    enabled: true
    ingressClassName: traefik
    annotations:
      cert-manager.io/cluster-issuer: tamoss-selfsigned
    hosts:
      - auth.tamoss.localtest.me
    tls:
      - secretName: authentik-localtest-tls
        hosts:
          - auth.tamoss.localtest.me
