apiVersion: tamoss.livewyer.io/v1alpha1
kind: Tamoss
metadata:
  labels:
    app.kubernetes.io/name: operator
    app.kubernetes.io/managed-by: kustomize
  name: tamoss-minimal
  namespace: tams
spec:
  version: dev
