package status

// Condition types exposed on Tamoss resources.
const (
	ConditionReady                      = "Ready"
	ConditionProgressing                = "Progressing"
	ConditionSchemaMigrated             = "SchemaMigrated"
	ConditionBackendsReady              = "BackendsReady"
	ConditionBackupPolicyReady          = "BackupPolicyReady"
	ConditionIdentityBlueprintSubmitted = "IdentityBlueprintSubmitted"
	ConditionIdentityReady              = "IdentityReady"
	ConditionUpgradeable                = "Upgradeable"
	ConditionRoutingReady               = "RoutingReady"
	ConditionHostnamesReady             = "HostnamesReady"
	ConditionLifecycleReady             = "LifecycleReady"
	ConditionDegraded                   = "Degraded"
	ConditionPaused                     = "Paused"
)

// StorageBackend condition types.
const (
	ConditionBucketReady               = "BucketReady"
	ConditionDatabaseReady             = "DatabaseReady"
	ConditionExternalS3DiagnosticReady = "ExternalS3DiagnosticReady"
)

// Reasons surfaced through Tamoss and StorageBackend status conditions,
// Kubernetes events, and reason-bearing metrics.
const ReasonAuthentikManagedBlueprintApplyRetrying = "AuthentikManagedBlueprintApplyRetrying"

const (
	ReasonAlreadyAtVersion                      = "AlreadyAtVersion"
	ReasonAllComponentsReady                    = "AllComponentsReady"
	ReasonAuthenticationDisabled                = "AuthenticationDisabled"
	ReasonAuthentikAPITokenMissing              = "AuthentikAPITokenMissing"
	ReasonAuthentikManagedBlueprintApplyFailed  = "AuthentikManagedBlueprintApplyFailed"
	ReasonAuthentikManagedBlueprintDeleteFailed = "AuthentikManagedBlueprintDeleteFailed"
	ReasonAPITokenRotationAccepted              = "APITokenRotationAccepted"
	ReasonAPITokenRotationRejected              = "APITokenRotationRejected"
	ReasonArtifactCleanupBlocked                = "ArtifactCleanupBlocked"
	ReasonArtifactCleanupComplete               = "ArtifactCleanupComplete"
	ReasonArtifactCleanupPending                = "ArtifactCleanupPending"
	ReasonArtifactCleanupRetained               = "ArtifactCleanupRetained"
	ReasonArtifactCleanupRetrying               = "ArtifactCleanupRetrying"
	ReasonBackendDependenciesAvailable          = "BackendDependenciesAvailable"
	ReasonBackendReferencesConfigured           = "BackendReferencesConfigured"
	ReasonBackupArchivingFailed                 = "BackupArchivingFailed"
	ReasonBackupArchivingUnknown                = "BackupArchivingUnknown"
	ReasonBackupPolicyConfigured                = "BackupPolicyConfigured"
	ReasonBackupPolicyDisabled                  = "BackupPolicyDisabled"
	ReasonBackupPolicyFailed                    = "BackupPolicyFailed"
	ReasonBackupPolicyHealthy                   = "BackupPolicyHealthy"
	ReasonBackupPolicyIncomplete                = "BackupPolicyIncomplete"
	ReasonBackupPolicyMissing                   = "BackupPolicyMissing"
	ReasonBackupPolicyNotManaged                = "BackupPolicyNotManaged"
	ReasonBackupPolicyPending                   = "BackupPolicyPending"
	ReasonBlueprintNotRequired                  = "BlueprintNotRequired"
	ReasonCORSMisconfigured                     = "CORSMisconfigured"
	ReasonBucketCreationFailed                  = "BucketCreationFailed"
	ReasonBucketDeletionComplete                = "BucketDeletionComplete"
	ReasonBucketDeletionRetrying                = "BucketDeletionRetrying"
	ReasonBucketDeletionSkipped                 = "BucketDeletionSkipped"
	ReasonBucketReady                           = "BucketReady"
	ReasonCNPGClusterReady                      = "CNPGClusterReady"
	ReasonCNPGSecretKeyMissing                  = "CNPGSecretKeyMissing"
	ReasonCNPGSecretsReady                      = "CNPGSecretsReady"
	ReasonClusterNotReady                       = "ClusterNotReady"
	ReasonComponentsProgressing                 = "ComponentsProgressing"
	ReasonDatabaseRegistered                    = "DatabaseRegistered"
	ReasonDatabaseRegistrationInProgress        = "DatabaseRegistrationInProgress"
	ReasonDatabaseRegistrationRetrying          = "DatabaseRegistrationRetrying"
	ReasonDriftCorrected                        = "DriftCorrected"
	ReasonExternalIdentityConfigured            = "ExternalIdentityConfigured"
	ReasonExternalS3DiagnosticReady             = "ExternalS3DiagnosticReady"
	ReasonExternalS3DiagnosticSkipped           = "ExternalS3DiagnosticSkipped"
	ReasonImagePullFailed                       = "ImagePullFailed"
	ReasonInvalidStorageBackendTags             = "InvalidStorageBackendTags"
	ReasonIssuerReachable                       = "IssuerReachable"
	ReasonIssuerUnreachable                     = "IssuerUnreachable"
	ReasonLifecycleBlocked                      = "LifecycleBlocked"
	ReasonLifecycleOperationDeleted             = "LifecycleOperationDeleted"
	ReasonLifecycleOperationConflict            = "LifecycleOperationConflict"
	ReasonManagedBlueprintApplied               = "ManagedBlueprintApplied"
	ReasonMigrationInProgress                   = "MigrationInProgress"
	ReasonMissingDependencyOperator             = "MissingDependencyOperator"
	ReasonMissingProviderConfiguration          = "MissingProviderConfiguration"
	ReasonMissingSecret                         = "MissingSecret"
	ReasonNoError                               = "NoError"
	ReasonNoRedirectURIDerivable                = "NoRedirectURIDerivable"
	ReasonPaused                                = "Paused"
	ReasonPlatformNamespaceNotAllowed           = "PlatformNamespaceNotAllowed"
	ReasonProviderBackendsReady                 = "ProviderBackendsReady"
	ReasonReconciliationActive                  = "ReconciliationActive"
	ReasonReconciliationPaused                  = "ReconciliationPaused"
	ReasonReconciling                           = "Reconciling"
	ReasonExternalRouting                       = "ExternalRouting"
	ReasonGatewayAPIUnavailable                 = "GatewayAPIUnavailable"
	ReasonHostnamesAccepted                     = "HostnamesAccepted"
	ReasonHibernateDestinationInvalid           = "HibernateDestinationInvalid"
	ReasonHibernateManifestChecksumMismatch     = "HibernateManifestChecksumMismatch"
	ReasonHibernateManifestUnavailable          = "HibernateManifestUnavailable"
	ReasonHibernateManifestUploadFailed         = "HibernateManifestUploadFailed"
	ReasonHibernateSourceInvalid                = "HibernateSourceInvalid"
	ReasonResumeSourceIgnored                   = "ResumeSourceIgnored"
	ReasonIngressConfigured                     = "IngressConfigured"
	ReasonIngressHostnamesConfigured            = "IngressHostnamesConfigured"
	ReasonNoRoutesRequired                      = "NoRoutesRequired"
	ReasonRoutePending                          = "RoutePending"
	ReasonRouteRejected                         = "RouteRejected"
	ReasonRoutesProgrammed                      = "RoutesProgrammed"
	ReasonSchemaApplied                         = "SchemaApplied"
	ReasonSchemaMigrationFailed                 = "SchemaMigrationFailed"
	ReasonSchemaNotReady                        = "SchemaNotReady"
	ReasonSchemaRetryAccepted                   = "SchemaRetryAccepted"
	ReasonSchemaRetryRejected                   = "SchemaRetryRejected"
	ReasonSecretReady                           = "SecretReady"
	ReasonSchemaMigrationSucceeded              = "SchemaMigrationSucceeded"
	ReasonStorageBackendBucketCreated           = "StorageBackendBucketCreated"
	ReasonStorageBackendBucketNotReady          = "StorageBackendBucketNotReady"
	ReasonStorageBackendBucketReady             = "StorageBackendBucketReady"
	ReasonStorageBackendNotManaged              = "StorageBackendNotManaged"
	ReasonStorageBackendNotReady                = "StorageBackendNotReady"
	ReasonStorageBackendReady                   = "StorageBackendReady"
	ReasonDatabaseRegistrationSkipped           = "DatabaseRegistrationSkipped"
	ReasonSourceDeprovisioning                  = "SourceDeprovisioning"
	ReasonTamossNotFound                        = "TamossNotFound"
	ReasonTamossHibernated                      = "TamossHibernated"
	ReasonTamossHibernating                     = "TamossHibernating"
	ReasonTamossReady                           = "TamossReady"
	ReasonTamossResuming                        = "TamossResuming"
	ReasonTargetNotQuiesced                     = "TargetNotQuiesced"
	ReasonTenantFailed                          = "TenantFailed"
	ReasonTenantNotReady                        = "TenantNotReady"
	ReasonEndpointUnreachable                   = "EndpointUnreachable"
	ReasonTLSValidationFailed                   = "TLSValidationFailed"
	ReasonUnsupportedHTTPRouteFilter            = "UnsupportedHTTPRouteFilter"
	ReasonUnsupportedSchemaVersion              = "UnsupportedSchemaVersion"
	ReasonUnsupportedProvider                   = "UnsupportedProvider"
	ReasonUpgradeNotEvaluated                   = "UpgradeNotEvaluated"
	ReasonUpgradeReady                          = "UpgradeReady"
	ReasonWaitingForSchema                      = "WaitingForSchema"
	ReasonWaitingForCNPGSecret                  = "WaitingForCNPGSecret"
)

const (
	PhasePending     = "Pending"
	PhaseProgressing = "Progressing"
	PhaseReady       = "Ready"
	PhaseDegraded    = "Degraded"
	PhasePaused      = "Paused"
	PhaseHibernating = "Hibernating"
	PhaseHibernated  = "Hibernated"
	PhaseResuming    = "Resuming"
	PhaseRunning     = "Running"
	PhaseSucceeded   = "Succeeded"
	PhaseFailed      = "Failed"
	PhaseBlocked     = "Blocked"
	PhaseUpgradeable = "Upgradeable"
	PhaseUnknown     = "Unknown"
	PhaseError       = "Error"
	PhaseIgnored     = "Ignored"
	PhaseFinalizing  = "Finalizing"
)
