{{- $values := (include "tams-platform.values" . | fromYaml) -}}
{{- $authentik := (default dict $values.authentikConfig) -}}
{{- if $authentik.enabled }}
{{- $secretName := default "tams-authentik" $authentik.secretName -}}
{{- $secrets := (default dict $authentik.secrets) -}}
{{- $oauth := (default dict $authentik.oauth) -}}
{{- $existing := lookup "v1" "Secret" $authentik.namespace $secretName -}}
{{- $existingAuthSecretKey := "" -}}
{{- $existingPostgresqlPassword := "" -}}
{{- $existingBootstrapPassword := "" -}}
{{- $existingBootstrapToken := "" -}}
{{- $existingClientSecret := "" -}}
{{- if $existing }}
  {{- if hasKey $existing.data "AUTHENTIK_SECRET_KEY" -}}
    {{- $existingAuthSecretKey = (index $existing.data "AUTHENTIK_SECRET_KEY" | b64dec) -}}
  {{- end -}}
  {{- if hasKey $existing.data "AUTHENTIK_POSTGRESQL__PASSWORD" -}}
    {{- $existingPostgresqlPassword = (index $existing.data "AUTHENTIK_POSTGRESQL__PASSWORD" | b64dec) -}}
  {{- end -}}
  {{- if hasKey $existing.data "AUTHENTIK_BOOTSTRAP_PASSWORD" -}}
    {{- $existingBootstrapPassword = (index $existing.data "AUTHENTIK_BOOTSTRAP_PASSWORD" | b64dec) -}}
  {{- end -}}
  {{- if hasKey $existing.data "AUTHENTIK_BOOTSTRAP_TOKEN" -}}
    {{- $existingBootstrapToken = (index $existing.data "AUTHENTIK_BOOTSTRAP_TOKEN" | b64dec) -}}
  {{- end -}}
  {{- if hasKey $existing.data "TAMOSS_OAUTH_CLIENT_SECRET" -}}
    {{- $existingClientSecret = (index $existing.data "TAMOSS_OAUTH_CLIENT_SECRET" | b64dec) -}}
  {{- end -}}
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  namespace: {{ $authentik.namespace }}
type: Opaque
stringData:
  AUTHENTIK_SECRET_KEY: {{ default (default (randAlphaNum 64) $existingAuthSecretKey) $secrets.authentikSecretKey | quote }}
  AUTHENTIK_POSTGRESQL__PASSWORD: {{ default (default (randAlphaNum 32) $existingPostgresqlPassword) $secrets.postgresqlPassword | quote }}
  AUTHENTIK_BOOTSTRAP_PASSWORD: {{ default (default (randAlphaNum 32) $existingBootstrapPassword) $secrets.bootstrapPassword | quote }}
  AUTHENTIK_BOOTSTRAP_TOKEN: {{ default (default (randAlphaNum 64) $existingBootstrapToken) $secrets.bootstrapToken | quote }}
  TAMOSS_OAUTH_CLIENT_SECRET: {{ default (default (randAlphaNum 48) $existingClientSecret) $oauth.clientSecret | quote }}
{{- end }}
