{{- $values := (include "tams-platform.values" . | fromYaml) -}}
{{- if ne $values.namespaces.app .Release.Namespace }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ $values.namespaces.app }}
  annotations:
    "helm.sh/resource-policy": keep
---
{{- end }}
{{- if ne $values.namespaces.auth $values.namespaces.app }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ $values.namespaces.auth }}
  annotations:
    "helm.sh/resource-policy": keep
{{- end }}
