{{- $values := (include "tams-platform.values" . | fromYaml) -}}
{{- $pg := (default dict $values.postgresqlAuth) -}}
{{- if and (default false $pg.enabled) (not $pg.existingSecret) }}
{{- $secretName := default "tams-postgresql-auth" $pg.secretName -}}
{{- $namespace := default .Release.Namespace $pg.namespace -}}
{{- $existing := lookup "v1" "Secret" $namespace $secretName -}}
{{- $secretKeys := default dict $pg.secretKeys -}}
{{- $usernameKey := default "username" $secretKeys.username -}}
{{- $passwordKey := default "password" $secretKeys.password -}}
{{- $databaseKey := default "database" $secretKeys.database -}}
{{- $username := default "tams" $pg.username -}}
{{- $password := "" -}}
{{- if $pg.password -}}
  {{- $password = $pg.password -}}
{{- else if and $existing (hasKey $existing.data $passwordKey) -}}
  {{- $password = (index $existing.data $passwordKey | b64dec) -}}
{{- else -}}
  {{- $password = randAlphaNum 32 -}}
{{- end -}}
{{- $database := default "tams" $pg.database -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  namespace: {{ $namespace }}
type: Opaque
stringData:
  {{ $usernameKey }}: {{ $username | quote }}
  {{ $passwordKey }}: {{ $password | quote }}
  {{ $databaseKey }}: {{ $database | quote }}
{{- end }}
