apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- https://github.com/livewyer-ops/tamoss/releases/download/__VERSION__/install.yaml
configMapGenerator:
- name: tamoss-installation-defaults
  namespace: tamoss-system
  files:
  - defaults.yaml
  options:
    immutable: true
patches:
- target:
    kind: Deployment
    name: operator-controller-manager
  patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: operator-controller-manager
    spec:
      template:
        spec:
          volumes:
          - name: instance-defaults
            configMap:
              name: tamoss-installation-defaults
